# Generated by Django 4.1.3 on 2022-12-15 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0002_post_title_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_tag',
        ),
    ]
